Backend
Arugaf/File-Synchronizer pull request #6
Opened 2020-04-15 15:28 UTC by Arugaf

2020-04-22 19:21 UTC, leshiy1295 commented on CMakeLists.txt
> +#set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wpedantic -Werror")
TODO

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/data_base_controller.h
> +#include <sys/inotify.h>
плохо, что в h-файле есть такая зависимость

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/data_base_controller.h
> +namespace fs = std::filesystem;
выносить namespace в header-файлах плохо

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/data_base_controller.h
> +        DataBaseController(const fs::directory_entry& path_to_files, std::shared_ptr<DataBase> data_base,
непонятно, почему DataBaseController зависит от файлов, да ещё и от конкретной реализации библиотечной реализации API...

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/local_data.h
> +        auto GetUserName();
кажется, можно было бы вынести в отдельную структуру со свойствами файла

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/local_data.h
> +        int current_transaction;
работу с транзакциями стоило бы вынести в отдельную сущность

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/local_data.h
> +        std::wstring user_name;
ох, проект ещё почти не начат, а уже wstring...

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/synch_controller.h
> +class DataBase;
а эти классы - не в namespace?

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/synch_controller.h
> +        static std::shared_ptr<SynchController> GetInstance(std::shared_ptr<DataBase> db, fs::path configure_file_path, int id);
почему два статических метода?
может, стоило сделать один, и уже у полученной сущности дозапрашивать, что нужно?

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/synch_controller.h
> +        int Synchronize();
методы не просто так разделены на группки - почему бы каждую не вынести в отдельные сущности с единой зоной ответственности?

2020-04-22 19:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/synch_controller.h
> +
кажется, что shared - это уже не про синглтон с точки зрения логики... ведь shared делит владение (!) между всеми потребителями...

2020-05-27 14:58 UTC, Arugaf commented
На предзащиту.

2020-06-01 15:30 UTC, leshiy1295 requested changes

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +                    std::unordered_map<std::string,
лучше напрямую set/map не использовать при обмене данными, в интерфейсе, так как её изменение повлечёт изменение интерфейса

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +        // TODO: Как избавиться от сырого указателя и стоит ли кидать указатель в конструктор для организации нормальной композиции вместо текущей dependency injection?
сырые указатели используются тогда, когда нужно отразить то, что владение объектом не требуется
если он сохраняется - лучше использовать shared_ptr

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +        bool IsIgnored(const std::string& file) const;
задача Watcher - следить за изменением состояния
само состояние - это уже отдельная сущность
стоило разбить этот класс на несколько

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +                case (FileStatus::Changed): {
стоило использовать цепочку ответственностей, чтобы можно было и другие более сложные сценарии можно было бы обрабатывать

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +    class FileWatcher {
в целом, можно было бы сделать и просто Watcher, который в принципе следит за чем-то, а FileWatcher - как его наследник, который реализует работу с файловой системой

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/SyncController.h
> +        std::unique_ptr<FileWatcher> file_watcher;
вот тогда можно было бы тут просто Watcher использовать

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/FileWatcher.cpp
> +            files[file.path().string()] = std::make_pair(std::filesystem::last_write_time(file),
вот лучше был бы не pair, а какой-нибудь класс File... Тогда название свойства было бы оправданным..

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/FileWatcher.cpp
> +    if (!std::filesystem::exists(this->path_to_watch)) {
используйте телескопическое свойство - делегирующие вызовы конструкторов, которое в C++11 появилось...

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/FileWatcher.cpp
> +        if (watching) {
if (!watching) { continue; }

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/FileWatcher.cpp
> +                auto file = files.begin();
for (auto &file : files) {}

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/FileWatcher.hpp
> +        bool mutable watching = true;
зачем помечено mutable? может быть, имелось в виду volatile?

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/SyncController.cpp
> +                std::cout << "created" << std::endl;
плохо, что сейчас идёт жёсткая привязка к std::couot
должен возвращаться статус, а уже клиент - на основе получаемого статуса должен дальше уже выводить что-нибудь в консоль, как вариант

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/SyncController.cpp
> +            HandleFileChangedEvent();
лучше было бы реализовать паттерн observer и уведомлять всех подписчиков при подобных событиях

2020-06-01 15:30 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/tests/FileWatcherTests.cpp
> +    std::string path("file_creating_ignored_file/");
тесты должны быть изолированными и не зависеть от файловой системы...
а для этого должны быть соответствующие возможности у интерфейса передать фейковую реализацию...

2020-06-01 16:21 UTC, leshiy1295 requested changes

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/ApplicationController.h
> +        void AddIgnoredFile(const fs::path& file);
Кажется, что лучше было работу с файлами выделить в отдельный контроллер
приложение же должно просто делегировать дальнейшее выполнение, например, именно этому контроллеру

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/DataBaseController.h
> +        std::unique_ptr<FileWatcher> file_watcher;
кажется, что DBController не должен зависеть от FileWatcher
должен быть FileController, который использует FileWatcher, и иногда передаёт управление DBController...

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/include/DataBaseWrapper.h
> +        std::unordered_map<std::filesystem::path, std::filesystem::file_time_type, std::hash<std::string>> GetAllFiles();
очень сложный тип...
нужно было использовать обёртку...

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/ApplicationController.cpp
> +    config_file /= "configure.cfg";
захардкожено :(
стоило передавать извне - например, через аргументы командной строки
ну или брать прямо название файла от working_path

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/CommandReader.cpp
> +    while (std::getline(std::cin, command)) {
Божественная функция

2020-06-01 16:21 UTC, leshiy1295 commented on File_Synchronizer_lib/Backend/src/CommandReader.cpp
> +    std::cout << "quit: Close application" << std::endl
стоило сделать через цепочку ответственности и обход их в цикле тут и в первом методе

2023-12-05 11:55 UTC, closed without merging